device_tracker:
  - platform: nmap_tracker
    hosts: 
      - 10.0.0.17
    home_interval: 10
    exclude: 10.0.0.34

vacuum:
  - platform: roomba
    host: [IP Address of your roomba. I set a static IP in my router.]
    username: [BLID from dorita980]
    password: [PASSWORD from dorita980]

ios:
  push:
    categories:
      - name: Vacuum
        identifier: 'vacuum'
        actions:
          - identifier: 'RUN_VACUUM'
            title: 'Start cleaning'
            activationMode: 'background'
            authenticationRequired: no
